version: "3"
services:
  api:
    container_name: "docker_dotnet_api"
    image: api-docker-sample
    build:
      context: .
      dockerfile: ./ApiDockerSample/Dockerfile
    ports:
      - 8000:80
